version: "3.9"
services:
  database:
    image: postgres:alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: enterprise-java-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  backend:
    build: .
    depends_on:
      - "database"
    ports:
    - 8080:8080